github actions conditional for continue-on-error

diff --git a/.github/workflows/conditionals.yml b/.github/workflows/conditionals.yml
--- a/.github/workflows/conditionals.yml
+++ b/.github/workflows/conditionals.yml
@@ -29,8 +29,8 @@ jobs:
       - name: only run on push events
         run: echo "Only run on push events"
         
-#       - name: step with continue-on-error
-#         run: |
-#           echo "This step will fail"
-#           exit 1
-#         continue-on-error: true
+      - name: step with continue-on-error
+        run: |
+          echo "This step will fail"
+          exit 1
+        continue-on-error: true
