fixed the error

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -42,7 +42,7 @@ jobs:
         run: |
           echo "Runner OS: ${{ runner.os}}"
 
-     #Step 6 Intentionally fail    
-      - name: Break the workflow on purpose
-        run: exit 1
+    #  #Step 6 Intentionally fail    
+    #   - name: Break the workflow on purpose
+    #     run: exit 1
     
