added error part

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -28,6 +28,10 @@ jobs:
       - name: Print the current date and time
         run: date
 
+         #Step 6 Intentionally fail    
+      - name: Break the workflow on purpose
+        run: exit 1
+
     # Step 4: Print branch name
       - name: Print branch name
         run: |
